version: '3.7'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql
    restart: always
    env_file:
      - .mysql.env
    ports:
      - "3306:3306"
#    volumes:
#      - clean_arch:/var/lib/mysql
#      - ./sql/creation.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clean_arch

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .rabbit.env
    networks:
      - clean_arch

  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapp
    ports:
      - "8080:8080"
      - "8088:8088"
      - "50051:50051"
    volumes:
      - .:/app
    networks:
      - clean_arch
    depends_on:
      rabbitmq:
        condition: service_healthy

#volumes:
#  clean_arch:

networks:
  clean_arch:
    driver: bridge
