### Create a order
POST http://localhost:8080/order HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "id":"D0133B1D-F67E-4747-A2CF-7AB04696A2F5",
    "price": 237.3,
    "tax": 0.8
}
